behaviors:
  ArcadeDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
      gail:
        gamma: 0.95
        strength: 0.1
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
        learning_rate: 0.0003
        use_actions: true
        demo_path: R:/Dev/Kart/Assets/Demo/LRvEX32.demo
    keep_checkpoints: 5
    max_steps: 1.0e7
    time_horizon: 10000
    summary_freq: 30000
